# semaphore-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: semaphore-secrets
  namespace: __NAMESPACE__
type: Opaque
data:
  mysql-password: '__MYSQL_PASSWORD_BASE64__'
  semaphore-admin-password: '__SEMAPHORE_ADMIN_PASSWORD_BASE64__'
  semaphore-access-key-encryption: '__SEMAPHORE_ACCESS_KEY_ENCRYPTION_BASE64__'

