# mysql-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: __NAMESPACE__
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# semaphore-lib-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semaphore-data-pvc
  namespace: __NAMESPACE__
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# semaphore-config-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semaphore-config-pvc
  namespace: __NAMESPACE__
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

