# 11_semaphore_requirements_configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: semaphore-requirements
  namespace: __NAMESPACE__
data:
  requirements.yml: |
    collections:
      - name: amazon.aws
      - name: ansible.netcommon
      - name: ansible.posix
      - name: ansible.utils
      - name: ansible.windows
      - name: awx.awx
      - name: azure.azcollection
        version: ">=2.1.0"
      - name: cisco.asa
      - name: cisco.ios
      - name: cisco.meraki
      - name: community.aws
      - name: community.ciscosmb
      - name: community.crypto
      - name: community.dns
      - name: community.docker
      - name: community.general
      - name: community.hashi_vault
      - name: community.libvirt
      - name: community.mongodb
      - name: community.mysql
      - name: community.network
      - name: community.okd
      - name: community.postgresql
      - name: community.rabbitmq
      - name: community.vmware
      - name: community.windows
      - name: community.zabbix
      - name: containers.podman
      - name: dellemc.unity
      - name: f5networks.f5_modules
      - name: fortinet.fortimanager
      - name: fortinet.fortios
      - name: google.cloud
      - name: hetzner.hcloud
      - name: infoblox.nios_modules
      - name: junipernetworks.junos
      - name: kubernetes.core
      - name: kubevirt.core
      - name: netapp.ontap
      - name: openstack.cloud
      - name: ovirt.ovirt
      - name: purestorage.flasharray
      - name: purestorage.flashblade
      - name: redhatinsights.insights
      - name: splunk.es
      - name: theforeman.foreman
      - name: vmware.vmware
      - name: vmware.vmware_rest
    roles:
      - src: https://github.com/joe-speedboat/ansible.os_update.git
        scm: git
        version: main
        name: joe-speedboat.os_update
      - name: joe-speedboat.template
  requirements.txt: |
    awxkit
    # ansible-pylibssh  # For SSH-based connections (ansible.netcommon, community.network, cisco.asa)
    boto3  # For AWS modules (amazon.aws, community.aws)
    botocore  # For AWS modules (amazon.aws, community.aws)
    cryptography  # Encryption-related tasks (hetzner.hcloud)
    deepdiff  # Deep object comparison (netapp.ontap)
    ansible-sign
    google-auth  # Google Cloud authentication (google.cloud)
    google-cloud-storage  # Google Cloud Storage API (google.cloud)
    grpcio  # gRPC support (ansible.netcommon)
    ipaddress  # IP address handling (netapp.ontap)
    isodate  # ISO date parsing (netapp.ontap)
    jmespath  # JSON queries (netapp.ontap)
    jsonpatch  # JSON patching (kubernetes.core)
    jsonschema  # JSON validation (ansible.utils)
    jxmlease  # XML processing (ansible.netcommon, junipernetworks.junos)
    kubernetes  # Kubernetes interaction (community.okd, kubernetes.core)
    ncclient  # NETCONF client (ansible.netcommon, junipernetworks.junos)
    netaddr  # Network address handling (ansible.utils, hetzner.hcloud)
    netapp-lib  # NetApp ONTAP library (netapp.ontap)
    paramiko  # Required for several networking modules (cisco.ios, cisco.asa, junipernetworks.junos)
    pexpect
    protobuf  # Required for gRPC (ansible.netcommon)
    psycopg2-binary  # PostgreSQL driver (community.postgresql)
    pyOpenSSL
    pyVmomi  # VMware interaction (community.vmware, vmware.vmware)
    # pykerberos
    # pypsrp[kerberos,credssp]
    pytest  # Testing framework (community.postgresql)
    pytest-mock  # Mocking for pytest (community.postgresql)
    python-daemon
    python-dateutil  # Date/time handling (hetzner.hcloud)
    # python_freeipa
    # pywinrm[kerberos,credssp]
    pyyaml
    receptorctl
    requests  # HTTP requests (google.cloud, netapp.ontap)
    requests-oauthlib  # OAuth handling for requests (community.okd, kubernetes.core)
    six  # Python 2/3 compatibility library (netapp.ontap)
    solidfire-sdk-python  # SolidFire SDK (netapp.ontap)
    textfsm  # Text processing (ansible.utils)
    toml
    ttp  # Text-to-Parser template processing (ansible.utils)
    vmware-vapi-common-client  # VMware API interaction (community.vmware)
    vmware-vcenter  # VMware vCenter interaction (community.vmware)
    xmltodict  # XML parsing (ansible.netcommon, ansible.utils, junipernetworks.junos)
